export const LoginConstants = {
    SET_SHOW: 'SET_SHOW',
    CLOSE_SHOW: 'CLOSE_SHOW',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    CLOSE_SHOW_SIGNUP: 'CLOSE_SHOW_SIGNUP',
    SET_SHOW_SIGNUP : 'SET_SHOW_SIGNUP',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE :'SIGNUP_FAILURE',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE',
    CLEAR_ERROR: 'CLEAR_ERROR'
}