export const productConstants = {
    GET_PRODUCT:'GET_PRODUCT',
    PRODUCT_BY_CATEGORY: 'PRODUCT_BY_CATEGORY',
    REQUEST_STARTED : 'REQUEST_STARTED',
    CREATE_PRODUCT_REQUEST : 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS : 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILED : 'CREATE_PRODUCT_FAILED'
}